export const curriculum = [
  { id: 1, order: 1, phase: "foundations", topic: "navigation", goal: "Understand SunVox interface", type: "lesson" },
  { id: 2, order: 2, phase: "foundations", topic: "routing", goal: "Connect modules correctly", type: "lesson" },
  { id: 3, order: 3, phase: "foundations", topic: "pattern_basics", goal: "Enter notes in patterns", type: "lesson" },
  { id: 4, order: 4, phase: "foundations", topic: "pulse", goal: "Feel steady pulse", type: "lesson" },
  { id: 5, order: 5, phase: "foundations", topic: "subdivision", goal: "Control rhythmic density", type: "lesson" },
  { id: 6, order: 6, phase: "foundations", topic: "velocity", goal: "Use velocity for dynamics", type: "lesson" },
  { id: 7, order: 7, phase: "foundations", topic: "fx_commands", goal: "Control notes with FX", type: "lesson" },
  { id: 8, order: 8, phase: "foundations", topic: "checkpoint_foundations", goal: "Build basic groove in SunVox", type: "checkpoint" },

  { id: 9, order: 9, phase: "melody", topic: "step_vs_leap", goal: "Hear step vs leap", type: "lesson" },
  { id: 10, order: 10, phase: "melody", topic: "oscillators", goal: "Understand basic sound sources", type: "lesson" },
  { id: 11, order: 11, phase: "melody", topic: "repetition", goal: "Use repetition for identity", type: "lesson" },
  { id: 12, order: 12, phase: "melody", topic: "envelopes", goal: "Shape sound with ADSR", type: "lesson" },
  { id: 13, order: 13, phase: "melody", topic: "motif_variation", goal: "Modify motifs", type: "lesson" },
  { id: 14, order: 14, phase: "melody", topic: "filters", goal: "Shape tone with filters", type: "lesson" },
  { id: 15, order: 15, phase: "melody", topic: "phrase", goal: "Build musical phrases", type: "lesson" },
  { id: 16, order: 16, phase: "melody", topic: "checkpoint_melody", goal: "Create melodic loop with sound design", type: "checkpoint" },

  { id: 17, order: 17, phase: "harmony", topic: "tonic", goal: "Feel tonal center", type: "lesson" },
  { id: 18, order: 18, phase: "harmony", topic: "chords", goal: "Build basic chords", type: "lesson" },
  { id: 19, order: 19, phase: "harmony", topic: "arrangement", goal: "Control density and layering", type: "lesson" },
  { id: 20, order: 20, phase: "harmony", topic: "progression", goal: "Create chord loops", type: "lesson" },
  { id: 21, order: 21, phase: "harmony", topic: "space", goal: "Use silence effectively", type: "lesson" },
  { id: 22, order: 22, phase: "harmony", topic: "pattern_structure", goal: "Structure patterns efficiently", type: "lesson" },
  { id: 23, order: 23, phase: "harmony", topic: "timing_control", goal: "Control groove with timing", type: "lesson" },
  { id: 24, order: 24, phase: "harmony", topic: "checkpoint_harmony", goal: "Build structured musical loop", type: "checkpoint" },

  { id: 25, order: 25, phase: "production", topic: "balance", goal: "Balance levels", type: "lesson" },
  { id: 26, order: 26, phase: "production", topic: "stereo", goal: "Use panning for clarity", type: "lesson" },
  { id: 27, order: 27, phase: "production", topic: "eq", goal: "Shape frequencies", type: "lesson" },
  { id: 28, order: 28, phase: "production", topic: "compression", goal: "Control dynamics", type: "lesson" },
  { id: 29, order: 29, phase: "production", topic: "reverb", goal: "Create space", type: "lesson" },
  { id: 30, order: 30, phase: "production", topic: "debugging", goal: "Fix common problems", type: "lesson" },
  { id: 31, order: 31, phase: "production", topic: "checkpoint_production", goal: "Clean and finalize loop", type: "checkpoint" },

  { id: 32, order: 32, phase: "integration", topic: "layers", goal: "Combine rhythm + melody", type: "lesson" },
  { id: 33, order: 33, phase: "integration", topic: "full_arrangement", goal: "Build multi-pattern track", type: "lesson" },
  { id: 34, order: 34, phase: "integration", topic: "variation", goal: "Create variation across patterns", type: "lesson" },
  { id: 35, order: 35, phase: "integration", topic: "mini_track", goal: "Create full short track", type: "lesson" },
  { id: 36, order: 36, phase: "integration", topic: "final_checkpoint", goal: "Complete structured track", type: "checkpoint" }
];